
server:
  port: 9292

front-end:
  url: "http://localhost:3000"
keycloak:
  client-id: "auth-client"
  client-secret: "T1lrAs44N7wsk1mfZxag54IXMO8NOOa1"
  introspect-url: "http://localhost:8080/realms/ya3ktest/protocol/openid-connect/token/introspect"
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/checklist"
    username: "root"
    password: "admin123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
