server:
  port: 9292

front-end:
  url: "http://localhost:3000"
back-end:
  url: "http://localhost:9292"
keycloak:
  client-id: "myclient"
  client-secret: "EXbUdVCyKJ5NUitgZi5CBINt85dkoNlx"
  introspect-url: "http://localhost:8080/realms/react-test/protocol/openid-connect/token/introspect"
spring:
  datasource:
    url: "jdbc:sqlserver://ThinkPad:1433;encrypt=true;trustServerCertificate=true;databaseName=test"
    username: "sa"
    password: "trang"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    properties:
      mail:
        smtp:
          auth=true:
          starttls:
            enable=true:
            required=true:
    username: "projectbygroup1@gmail.com"
    port: 587
    host: "smtp.gmail.com"
    password: "memx qifl jhbw hacz"

cron expression: '0 * * * * ? '   # sau 1p gui mail 1 lan
  #Co the chon cai dat send mail theo nhung moc thoi gian sau:
  # cron expression: '0 0 20 ? * MON'     :  8h moi toi thu 2 se gui mail 1 lan
  # cron expression: '0 0 20 ? * MON-FRI' :  8h moi toi thu 2-thu 6 se gui mail 1 lan
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: info