
server:
  port: 9292

front-end:
  url: "http://localhost:3000"
keycloak:
  client-id: "myclient"
  client-secret: "EXbUdVCyKJ5NUitgZi5CBINt85dkoNlx"
  introspect-url: "http://localhost:8080/realms/react-test/protocol/openid-connect/token/introspect"
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/checklist"
    username: "root"
    password: "23012003aA@"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

