server:
  port: 9292

front-end:
  url: "http://localhost:3000"
back-end:
  url: "http://localhost:9292"
keycloak:
  client-id: "auth-client"
  client-secret: "T1lrAs44N7wsk1mfZxag54IXMO8NOOa1"
  introspect-url: "http://localhost:8080/realms/ya3ktest/protocol/openid-connect/token/introspect"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/checklist"
    username: "root"
    password: "dongloi123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    properties:
      mail:
        smtp:
          auth=true:
          starttls:
            enable=true:
            required=true:
    username: "projectbygroup1@gmail.com"
    port: 587
    host: "smtp.gmail.com"
    password: "memx qifl jhbw hacz"

cron expression: '0 0 * * * ? '   # sau 1 hour gui mail 1 lan
  #Co the chon cai dat send mail theo nhung moc thoi gian sau:
  # cron expression: '0 0 20 ? * MON'     :  8h moi toi thu 2 se gui mail 1 lan
# cron expression: '0 0 20 ? * MON-FRI' :  8h moi toi thu 2-thu 6 se gui mail 1 lan
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html


logging:
  level:
    root: info

