
server:
  port: 9292

front-end:
  url: "http://localhost:5173"
keycloak:
  client-id: "myclient"
  client-secret: "T1lrAs44N7wsk1mfZxag54IXMO8NOOa1"
  introspect-url: "http://localhost:8080/realms/react-test/protocol/openid-connect/token/introspect"
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/checklist"
    username: "root"
    password: "admin123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
