server:
  port: 9292

front-end:
  url: "http://localhost:3000"
back-end:
  url: "http://localhost:9292"
keycloak:
  client-id: "auth-client"
  realm: "ya3ktest"
  client-secret: "T1lrAs44N7wsk1mfZxag54IXMO8NOOa1"
  introspect-url: "http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/token/introspect"


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/checklist"
    username: "root"
    password: "23012003aA@"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

response:
  success:
    code: 200
  not-found:
    code: 404
  bad-request:
    code: 400
  unauthorized:
    code: 401
  internal-server-error:
    code: 500

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html


#logging:
#  level:
#    root: info
#
# Logging configuration
logging:
  level:
    root: Info
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%6X{requestId}]){faint} %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:%wEx}){red}"


