server:
  port: 9292

front-end:
  url: "http://localhost:3000"
back-end:
  url: "http://localhost:9292"
keycloak:
  client-id: "myclient"
  client-secret: "EXbUdVCyKJ5NUitgZi5CBINt85dkoNlx"
  introspect-url: "http://localhost:8080/realms/react-test/protocol/openid-connect/token/introspect"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/checklist"
    username: "root"
    password: "23012003aA@"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html


#logging:
#  level:
#    root: info
#
# Logging configuration
logging:
  level:
    root: Info


