server:
  port: ${SERVER_PORT}

frontend:
  url: ${FRONTEND_URL}
backend:
  url: "http://localhost:9292"
keycloak:
  client: ${KEYCLOAK_CLIENT}
  realm: ${KEYCLOAK_REALM}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  introspect-url: "http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/token/introspect"
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/checklist?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:23012003aA@}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

response:
  success:
    code: 200
  not-found:
    code: 404
  bad-request:
    code: 400
  unauthorized:
    code: 401
  internal-server-error:
    code: 500

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
      hibernate: off
      apache.catalina: off
    com.zaxxer: off
    root: ${LOGGING_LEVEL_ROOT}
  pattern:
    console: "%clr(CheckList_project){faint}  %clr(%-40.40logger{39}){cyan} %clr(%23.23M){green} %clr(%d{yyyy-MM-dd E HH:mm:ss}){faint} %clr([%6X{requestId}]){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:%wEx}){red}"


#  pattern:
#    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%6X{requestId}]){faint} %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:%wEx}){red}"

