server:
  port: ${BE_PORT}

front-end:
  url: ${FE_URL}
back-end:
  url: "http://localhost:9292"
keycloak:
  client-id: ${KEYCLOAK_CLIENT}
  realm: ${KEYCLOAK_REALM}
  client-secret: ${KEYCLOAK_SECRET_CLIENT}
  introspect-url: "http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/token/introspect"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checklist?useSSL=false&createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

response:
  success:
    code: 200
  not-found:
    code: 404
  bad-request:
    code: 400
  unauthorized:
    code: 401
  internal-server-error:
    code: 500

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework: ${SPRING_LOG_LEVEL_ROOT}
      hibernate: off
      apache.catalina: off
    com.zaxxer: off
    root: ${LOGGING_LEVEL_ROOT}
  pattern:
    console: "%clr(CheckList_project){faint}  %clr(%-40.40logger{39}){cyan} %clr(%23.23M){green} %clr(%d{yyyy-MM-dd E HH:mm:ss}){faint} %clr([%6X{requestId}]){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:%wEx}){red}"


#  pattern:
#    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%6X{requestId}]){faint} %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:%wEx}){red}"

